# make this unique
name: First Workflow

# when the work flow should run: Event (there are multiple we use workflow_dispatch here)
# workflow_dispatch -->>> requires user to manually trigger the workflow
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

on: workflow_dispatch
# : schedule
#     - cron:  '30 5,17 * * *'

# the work or tasks to be done/executed
# takes many Job
jobs:
  # first job to be executed
  first-job:
    # runner (an OS/ENV -->> search 'github action runner' > About GitHub-hosted runners > scroll down to see supported runners)
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        # script or command -->> for actions, **uses** is the keyword
        run: echo 'Hello World'
      - name: Print goodbye
        # running multu line command in one step
        run: |
          echo "Done - bye"
          echo "God is good"
    
